
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      ai_agent:
        condition: service_healthy
    volumes:
    - ./backend:/app 
    - db_data:/app/db/backend.db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend
  
  ai_agent:
    build: ./ai_agent
    ports:
      - "8003:8003"
    networks:
      - app-network
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  



