
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    depends_on:
      ai_agent:
        condition: service_healthy
    volumes:
    - ./backend:/app 
      - db_data:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend
  
  ai_agent:
    build: ./ai_agent
    ports:
      - "8003:8003"
      - "11434:11434"  # Add Ollama's port
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data:
  db_data:
  



